// <auto-generated />
using DataAuthority.SqlServerEF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DataAuthority.SqlServerEF.Migrations
{
    [DbContext(typeof(DataAuthorityContext))]
    partial class DataAuthorityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataAuthority.DataInfrastructure.DataModels.PayLoadDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Data")
                        .IsRequired();

                    b.Property<string>("Origin")
                        .IsRequired();

                    b.Property<int>("ProvidedPayLoadId");

                    b.HasKey("Id");

                    b.ToTable("PayLoad");
                });
#pragma warning restore 612, 618
        }
    }
}
